from check_temperature import check_temperature
if __name__ == '__main__':
  assert(check_temperature(20,"C") is True)
  assert(check_temperature(30,"C") is True)
  assert(check_temperature(40,"C") is True)
  assert(check_temperature(45,"C") is True)
  assert(check_temperature(0,"C") is True)
  assert(check_temperature(-3,"C") is False)
  assert(check_temperature(46,"C") is False)
  assert(check_temperature(54,"C") is False)
  assert(check_temperature(95,"F") is True)
  assert(check_temperature(32,"F") is True)
  assert(check_temperature(111,"F") is True)
  assert(check_temperature(21,"F") is False)
  assert(check_temperature(140,"F") is False)
  assert(check_temperature(32,"F") is True)
  assert(check_temperature(77,"F") is True)
  assert(check_temperature(120,"F") is False)