from check_soc import check_soc
if __name__ == '__main__':
  assert(check_soc(20) is True)
  assert(check_soc(18) is False)
  assert(check_soc(40) is True)
  assert(check_soc(45) is True)
  assert(check_soc(0) is False)
  assert(check_soc(-3) is False)
  assert(check_soc(46) is False)
  assert(check_soc(54) is False)
  assert(check_soc(95) is False)
  assert(check_soc(32) is True)
  assert(check_soc(111) is False)
  assert(check_soc(21) is True)
  assert(check_soc(140) is False)
  assert(check_soc(32) is True)
  assert(check_soc(77) is True)
  assert(check_soc(120) is False)